deployments:
  deploymentGating:
    enabled: true # to enable the feature
    retry: 50 # run poll action 50 times
    sleep: 30 # wait 30 seconds between each poll
    environments: # select the environments you'd like to use with this feature
    - Production
  services:
    ids:
    - ari:cloud:graph::service/52e1a171-c6c1-45fa-a211-9e61ec27a7b4/22402f4e-08c6-11f0-8334-0afff3dd3477
